escapedjsystem/escapedjsystem/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'escapedjsystem.escapedjsystem.views.home', name='home'),

    url(r'^djview', 'escapedjsystem.escapedjsystem.views.djview', name='djview'),

    url(r'^newmessage', 'escapedjsystem.escapedjsystem.views.newmessage', name='newmessage'),
    url(r'^songrequest', 'escapedjsystem.escapedjsystem.views.songrequest', name='songrequest'),

    url(r'^getmessages', 'escapedjsystem.escapedjsystem.views.getmessages', name='getmessages'),
    url(r'^getsongrequests', 'escapedjsystem.escapedjsystem.views.getsongrequests', name='getsongrequests'),

    url(r'^about', 'escapedjsystem.escapedjsystem.views.about', name='about'),

)

escapedjsystem/urls.py
from django.conf.urls import patterns, include, url

from django.http import HttpResponseRedirect


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^$', lambda x: HttpResponseRedirect('/escapedjsystem/')),

    url(r'^escapedjsystem/', include('escapedjsystem.escapedjsystem.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

escapedjsystem/escapedjsystem/models.py
from django.db import models


class Song(models.Model):
    text = models.CharField(max_length=80)
    date = models.DateTimeField(auto_now_add=True)


class SongRequest(models.Model):
    song = models.ForeignKey(Song)
    date = models.DateTimeField(auto_now_add=True)
    played = models.BooleanField(default=False)


class Message(models.Model):
    text = models.CharField(max_length=140)  # Length of a twitter message
    date = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)

escapedjsystem/escapedjsystem/forms.py
from django import forms
from models import *


class NewMessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(NewMessageForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['text'].widget.attrs.update({
            'placeholder': 'Ex: Turn up the volume!',
            'class': 'input-block-level'
        })


class SongRequestForm(forms.Form):
    song = forms.CharField(max_length=80)

    def __init__(self, *args, **kwargs):
        super(SongRequestForm, self).__init__(*args, **kwargs)
        self.fields['song'].label = ''
        self.fields['song'].widget.attrs.update({
            'autocomplete': 'off',
            'placeholder': 'Ex: Numb/Encore by Linkin Park and Jay-Z',
            'class': 'input-block-level'
        })

escapedjsystem/escapedjsystem/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import RequestContext
from django.shortcuts import render_to_response
from models import Message, Song, SongRequest
from forms import NewMessageForm, SongRequestForm
from django.views.decorators.csrf import ensure_csrf_cookie

from datetime import timedelta
import simplejson
from time import sleep

from django.utils.timezone import localtime, now

from django.db import transaction
from django.conf import settings

#############################################################


@transaction.commit_manually
def flush_transaction():
    """
    Flush the current transaction so we don't read stale data

    Use in long running processes to make sure fresh data is read from
    the database.  This is a problem with MySQL and the default
    transaction mode.  You can fix it by setting
    "transaction-isolation = READ-COMMITTED" in my.cnf or by calling
    this function at the appropriate moment
    """
    transaction.commit()


def alerthtml(alertype, title, message):
    return """<div class="alert %s fade">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>%s</strong> %s
    </div><script>$('.alert').closest('.alert').fadeIn(1).addClass('in')</script>""" % (alertype, title, message)
    #Todo: improve (make code prettier) javascript fadein


def render_helper(template, c, request):

    c['bootstrap_style'] = settings.BOOTSTRAP_STYLE

    return render_to_response(template, RequestContext(request, c))

####################################################################


@ensure_csrf_cookie
def home(request):
    c = {}
    c['title'] = 'Escape DJ System'

    c['songrequests'] = SongRequest.objects.order_by('-pk')[:5]
    c['newMessageForm'] = NewMessageForm()
    c['songRequestForm'] = SongRequestForm()

    #Previous songs for typeahead
    c['songs'] = Song.objects.order_by('-date')[:500]

    return render_helper('esc_home.html', c, request)


@ensure_csrf_cookie
def djview(request):
    c = {}
    c['title'] = 'Escape DJ View'

    c['msgs'] = Message.objects.order_by('-pk')[:7]
    c['songrequests'] = SongRequest.objects.order_by('-pk')[:7]

    # c['bootstrap_style'] = 'slate'

    if request.method == "GET" and 'fullscreen' in request.GET:
        c['fullscreen'] = True

    return render_helper('esc_djview.html', c, request)


def about(request):
    c = {}
    c['title'] = ''

    return render_helper('esc_about.html', c, request)


def newmessage(request):

    c = {}

    if request.method == 'POST':
        newMessageForm = NewMessageForm(request.POST)
        if newMessageForm.is_valid():
            newMessageForm.save()
            response = alerthtml('alert-success', 'Success!', 'Your message was sent to the DJ')
        else:
            response = alerthtml('alert-error', 'Error!', 'Please fill in all fields!')

        if request.is_ajax():
            return HttpResponse(simplejson.dumps({'html': response}), content_type="application/json")
        else:
            c['newmessage_result'] = response

    c['title'] = 'Send a message to the DJ'

    c['newMessageForm'] = NewMessageForm()
    return render_helper('esc_newmessage.html', c, request)


def songrequest(request):

    c = {}
    c['title'] = 'Request a song'

    if request.method == 'POST':
        songRequestForm = SongRequestForm(request.POST)
        response = ''
        if songRequestForm.is_valid():
            try:
                song = Song.objects.get(text=songRequestForm.cleaned_data['song'])
            except Song.DoesNotExist:
                song = Song(text=songRequestForm.cleaned_data['song'])
                song.save()

            #Check if same song has been requested in the last 15 min
            lastSongRequests = SongRequest.objects.filter(date__gte=(now() - timedelta(minutes=15)))

            for x in lastSongRequests:
                if x.song == song:
                    response = alerthtml('alert-error', 'Error!', 'That song has already been requested in the last 15 minutes')
                    break
            else:
                songRequest = SongRequest(song=song)
                songRequest.save()
                response = alerthtml('alert-success', 'Success!', 'Your song has been requested')

        else:
            response = alerthtml('alert-error', 'Error!', 'Please fill in all fields!')

        if request.is_ajax():
            return HttpResponse(simplejson.dumps({'html': response}), content_type="application/json")
        else:
            c['songrequest_result'] = response

    c['songRequestForm'] = SongRequestForm()

    #Previous songs for typeahead
    c['songs'] = Song.objects.order_by('-date')[:500]

    return render_helper('esc_songrequest.html', c, request)


def getmessages(request):

    if not request.method == "POST":
        return HttpResponseBadRequest()

    if 'pk' not in request.POST:
        return HttpResponseBadRequest()

    pk = request.POST['pk']
    for _ in xrange(20):
        messages = Message.objects.filter(pk__gt=pk).order_by('pk')[:100]
        flush_transaction()
        if messages:
            jmessages = []
            for x in messages:
                jmessages.append(
                    {
                        'pk': x.pk,
                        'text': x.text,
                        'seen': x.seen,
                        'date': localtime(x.date).strftime("%c")
                    }
                )
            return HttpResponse(simplejson.dumps(jmessages), content_type="application/json")

        sleep(1)

    return HttpResponse('OK')


def getsongrequests(request):
    if not request.method == "POST":
        return HttpResponseBadRequest()

    if 'pk' not in request.POST:
        return HttpResponseBadRequest()

    pk = request.POST['pk']
    for _ in xrange(60):
        songs = SongRequest.objects.filter(pk__gt=pk).order_by('pk')[:100]
        flush_transaction()
        if songs:
            jsongs = []
            for x in songs:
                jsongs.append(
                    {
                        'pk': x.pk,
                        'text': x.song.text,
                        'played': x.played,
                        'date': localtime(x.date).strftime("%c")
                    }
                )
            return HttpResponse(simplejson.dumps(jsongs), content_type="application/json")

        sleep(1)

    return HttpResponse('OK')

escapedjsystem/escapedjsystem/templates/esc_about.html
{% extends "esc_base.html" %}

{% block content %}

<div class="hero-unit" id="about">

<h1>About</h1>
<p>Escape DJ System is a web application for use in <a href="http://cyb.no">CYB's</a> Student Pub, Escape.</p>
<p></p>
<img class="img-rounded" src="http://cyb.ifi.uio.no/logo/hvittpasort.png" />

<p>With Escape DJ System you can requests songs you want to hear the DJ play, and even send him/her messages!</p>

<p>The DJ sees all incomming song requests and messages on a dedicated screen in the DJ booth.</p>

</div>

{% endblock %}

escapedjsystem/escapedjsystem/templates/esc_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% if bootstrap_style %}
      <link href="{{ STATIC_URL }}/css/bootstrap-{{ bootstrap_style }}.min.css" rel="stylesheet">
    {% else %}
      {% comment %} cosmo cyborg orginal slate spacelab {% endcomment %}
      {% with "slate" as bootstrap_style %}
      <link href="{{ STATIC_URL }}/css/bootstrap-{{ bootstrap_style }}.min.css" rel="stylesheet">
      {% endwith %}
    {% endif %}

    <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.timesince.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.cookie.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.2.custom.min.js"></script>

    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <!--<script src="{{ STATIC_URL }}js/spin.min.js"></script> -->
    <script src="{{ STATIC_URL }}js/bootstrap-ajax.js"></script>

    <style>
      body {
        padding-top:60px;
        word-wrap: break-word;
      }
      #main {

      }
      .message {

      }
      .songrequest {

      }
      #about p {
     
      }
      #about h1 {
        margin-bottom:20px;
      }
      #about img {
        margin-bottom:20px;
      }
      #fullscreenButton {

      }

    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Fav and touch icons -->
    {% comment %}
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    {% endcomment %}
    <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url "home" %}">Escape DJ System</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="{% block nav-home-class %}{% endblock %}"><a href="{% url "home" %}">Home</a></li>
              <li class="{% block nav-djview-class %}{% endblock %}"><a href="{% url "djview" %}">DJ View</a></li>
              <li class="{% block nav-songrequest-class %}{% endblock %}"><a href="{% url "songrequest" %}">Request a Song</a></li>
              <li class="{% block nav-newmessage-class %}{% endblock %}"><a href="{% url "newmessage" %}">Send a Message</a></li>
              <li class="{% block nav-about-class %}{% endblock %}"><a href="{% url "about" %}">About</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" id="main">

      <h1 id="title_h1">{{ title }}</h1>
      {% block content %}{% endblock %}
    </div> <!-- /container -->


  </body>
</html>

escapedjsystem/escapedjsystem/templates/esc_djview.html
{% extends "esc_base.html" %}
{% block nav-djview-class %}active{% endblock %}

{% block content %}
<div class="row">
<div class="span12">
	<button id="fullscreenButton" class="btn pull-right">Go Fullscreen</button>
</div>
</div>

<div class="row">
{% include "esc_elementlist.html" with e_name="songrequest" e_names="songrequests" e_title="Song Requests" e_url="getsongrequests" e_max="7" e_elements=songrequests span_value="span6" offset_value="" %}

{% include "esc_elementlist.html" with e_name="message" e_names="messages" e_title="Messages" e_url="getmessages" e_max="7" e_elements=msgs span_value="span6" offset_value="" %}
</div>


<script type="text/javascript">
$(document).ready(function() {

	window.fullscreenState = 0;

	$(window).on('hashchange', function() {
		if (window.location.hash == "#fullscreen") {
			makeFullscreen();
			$('#fullscreenButton').html('Exit Fullscreen');
		}
		//We remove the button the page is displayed on a single purpose monitor
		else if (window.location.hash == "#fullscreenmonitor") {
			makeFullscreen();
			$('#fullscreenButton').fadeOut();
			window.maxsongrequests = 10;
			window.maxmessages = 10;
			window.fullscreenmonitor = 1;
			$('.container').css({'margin-top':'20px'}); //If we need to lower the view
			$("<link/>", { //Load the dark css for monitor viewing
			   rel: "stylesheet",
			   type: "text/css",
			   href: "{{ STATIC_URL }}/css/bootstrap-slate.min.css"
			}).appendTo("head"); 
		}
	});
	$(window).trigger('hashchange');
	
	$('#fullscreenButton').on('click', function() {
		if (window.fullscreenState == 0) {
			makeFullscreen();
			$(this).html('Exit Fullscreen');
		}
		else {
			unfullScreen();
			$(this).html('Go Fullscreen');
		}
	});

});

//We make it fullscreen client side
function makeFullscreen(){
	$('.navbar').add('#title_h1').fadeOut('fast',function() {
		$('body').css({'padding-top':'123px'}).animate({'padding-top':'0'}, 'fast');
	});

	window.fullscreenState = 1;
}
function unfullScreen() {
	
	$('body').animate({'padding-top':'123px'}, 'fast', function() {
		$('.navbar').add('#title_h1').fadeIn('fast');
		$('body').css({'padding-top':'60px'});
	});
	window.fullscreenState = 0;	
}
</script>

{% endblock %}

escapedjsystem/escapedjsystem/templates/esc_elementlist.html
{% comment %}
Requires:
{{e_name}} {{e_names}} {{e_title}} {{e_url}} {{e_max}} {{ e_elements }} {{ span_value }} {{ offset_value }}
{% endcomment %}
<div class="{{ span_value }} {{ offset_value }}" id="{{ e_names }}">
	<h2>{{ e_title }}</h2>
	{% for x in e_elements %}
		<div class="row">
			<div class="{{ span_value }}">
				<div class="well well-small {{ e_name }}" id="{{ e_name }}_{{x.pk}}">
					<span class="pull-right muted timesince" title="{{x.date|date:"c"}}">{{ x.date|timesince }}</span>
					<span class="">{% if x.text %}{{x.text}}{% else %}{{x.song.text}}{% endif %}</span>
				</div>
			</div>
		</div>
	{% empty %}
		<div class="row">
			<div class="{{ span_value }}">
				<div class="well well-small" id="{{ e_names }}_empty">
					<i class="icon-info-sign pull-right"></i>
					<p class="text-info">There doesn't seem to be any {{e_names}} submited</p>
				</div>
			</div>
		</div>
	{% endfor %}
</div>

<script type="text/javascript">
$(document).ready(function() {

var csrftoken = $.cookie('csrftoken');

var {{e_names}} = new Array();

window.max{{e_names}} = ({{ e_elements|length }} > {{ e_max }} ? {{ e_elements|length }} : {{ e_max }});

{% for x in e_elements %}{{e_names}}[{{forloop.counter0}}] = {{ x.pk }};
{% empty %}
{{e_names}}[0] = 0;
{% endfor %}

//Timesince
$("#{{e_names}}").find(".timesince").timesince({
    refreshMs: 1 * 60 * 1000 // 1 minute
});

(function {{e_name}}_poll(){
	setTimeout(function(){
    $.ajax({ url: "{% url e_url %}", 
    	beforeSend: function(xhr, settings) {
        	xhr.setRequestHeader("X-CSRFToken", csrftoken );
    	},
    	success: function(data){

	        for (var i = 0; i < data.length; i++) {
	        	{{e_names}}.unshift(data[i]['pk']);
			}

			//Remove empty notice, if it exists
			if ($('#{{ e_names }}_empty').length > 0) {
				$('#{{ e_names }}_empty').remove();
			}

			//Remove old elements
			while(window.max{{e_names}} < {{e_names}}.length) {
				$('#{{e_name}}_' + {{e_names}}.pop() ).remove();
			}
			//Add new elements
	        for (var i = 0; i < data.length; i++) {
	        	$('<div class="row">\
		        		<div class="{{ span_value }}">\
			        		<div class=\"well well-small {{e_name}}\" id=\"{{e_name}}_'+ data[i]['pk'] +'\">\
								<span class=\"pull-right muted timesince\" title=\"' + data[i]['date'] + '\"></span>\
								<span class=\"\">' + data[i]['text'] + '</span>\
							</div>\
						</div>\
					</div>\
	        		').hide().insertAfter( $('#{{e_names}}').find('h2') ).fadeIn().find('.timesince').timesince({refreshMs: 1 * 60 * 1000});

			}

			if (window.fullscreenmonitor > 0 && window.fullscreenmonitor != 2) {
				window.fullscreenmonitor = 2;
				$('body').effect( "highlight", {color:"rgba(0, 0, 25, 0.5)"}, 1000 );
				$('body').promise().done(function() {
					window.fullscreenmonitor = 1;
				});
			}
	  
    	}, dataType: "json", complete: {{e_name}}_poll, timeout: 90000, type:'POST', data:{'pk':{{e_name}}s[0]} } );
    },500);
})();

});

</script>

escapedjsystem/escapedjsystem/templates/esc_home.html
{% extends "esc_base.html" %}
{% block nav-home-class %}active{% endblock %}
{% block content %}

<div class="row">
<div class="span12">
	<div class="well">
        <p>Welcome to Escape DJ System. Here you can request songs and send messsages to the DJ</p>
        <p>The DJ will instantaneously recive your lovely requests and flattering messages on a dedicated monitor in the DJ booth.</p>
        <p>So go ahead, request a song you would love to hear, or tell the DJ how awesome he/she is!</p>
    </div>
</div>
</div>

<div class="row">
{% include "esc_songrequest_form.html" with span_value="span6" form_title="Request a Song!" %}
{% include "esc_newmessage_form.html" with span_value="span6" form_title="Send a message to the DJ!" %}
</div>

<div class="row">
{% include "esc_elementlist.html" with e_name="songrequest" e_names="songrequests" e_title="Song Requests" e_url="getsongrequests" e_max="5" e_elements=songrequests span_value="span12" offset_value="" %}
</div>

<script type="text/javascript">
$('#id_song').focus();
</script>

{% endblock %}

escapedjsystem/escapedjsystem/templates/esc_newmessage.html
{% extends "esc_base.html" %}

{% load bootstrap_toolkit %}

{% block nav-newmessage-class %}active{% endblock %}
{% block content %}
<div class="row">
{% include "esc_newmessage_form.html" with span_value="span12" %}
</div>
{% endblock %}

escapedjsystem/escapedjsystem/templates/esc_newmessage_form.html
{% load bootstrap_toolkit %}

<div class="{{ span_value }}">

<h2>{{ form_title }}</h2>
<div id="newmessage_result" class="form_result">
{% if newmessage_result %}
{% autoescape off %}
{{ newmessage_result }}
{% endautoescape %}
{% endif %}
</div>

<div class="well">
<form action="{% url "newmessage" %}" method="post" class="ajax" data-replace-inner="#newmessage_result" data-method="post">
	{% csrf_token %}
	{{ newMessageForm|as_bootstrap }}
	<div class="control-group">
		<div class="controls">
			<input type="submit" class="btn" value="Send message" />
		</div>
	</div>
</form>
</div>

<script type="text/javascript">

$('#id_text').focus();
</script>

</div>

escapedjsystem/escapedjsystem/templates/esc_songrequest.html
{% extends "esc_base.html" %}
{% load bootstrap_toolkit %}

{% block nav-songrequest-class %}active{% endblock %}
{% block content %}
<div class="row">
{% include "esc_songrequest_form.html" with span_value="span12" %}
</div>
{% endblock %}

escapedjsystem/escapedjsystem/templates/esc_songrequest_form.html
{% load bootstrap_toolkit %}

<div class="{{ span_value }}">

<h2>{{ form_title }}</h2>
<div id="songrequest_result" class="form_result">
{% if songrequest_result %}
{% autoescape off %}
{{ songrequest_result }}
{% endautoescape %}
{% endif %}
</div>

<div class="well">
<form id="songrequest_form" action="{% url "songrequest" %}" method="post" class="ajax" data-replace-inner="#songrequest_result" data-method="post">
    {% csrf_token %}
    {{ songRequestForm|as_bootstrap }}
    <div class="control-group">
		<div class="controls">
  			<input type="submit" value="Request Song" class="btn" />
		</div>
	</div>
</form>
</div>

<script type="text/javascript">

var songs = [{% for x in songs %}'{{x.text}}',{% endfor %}]
 
$('#id_song').typeahead({source: songs}).focus();

//When a a song request is submited, add it to the song array
$('#songrequest_form').submit(function(){
	songs.push($('#id_song').val() );
});

</script>



</div>